// apps/web/src/components/ui/select.tsx
'use client';

import { Select as SelectPrimitive } from '@base-ui/react/select';
import { Check, ChevronDown } from 'lucide-react';
import * as React from 'react';

import { cn } from '@/lib/utils';

function Select({ ...props }: SelectPrimitive.Root.Props<string>) {
	return <SelectPrimitive.Root data-slot="select" {...props} />;
}

function SelectTrigger({
	className,
	children,
	...props
}: SelectPrimitive.Trigger.Props) {
	return (
		<SelectPrimitive.Trigger
			data-slot="select-trigger"
			className={cn(
				'flex h-8 w-full items-center justify-between gap-2 rounded-lg border border-input bg-transparent px-2.5 py-1 text-sm transition-colors outline-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 disabled:pointer-events-none disabled:cursor-not-allowed disabled:bg-input/50 disabled:opacity-50 data-placeholder:text-muted-foreground',
				className,
			)}
			{...props}
		>
			{children}
			<SelectPrimitive.Icon className="text-muted-foreground">
				<ChevronDown className="size-4" />
			</SelectPrimitive.Icon>
		</SelectPrimitive.Trigger>
	);
}

function SelectValue({ ...props }: SelectPrimitive.Value.Props) {
	return <SelectPrimitive.Value data-slot="select-value" {...props} />;
}

function SelectContent({
	className,
	children,
	...props
}: SelectPrimitive.Popup.Props) {
	return (
		<SelectPrimitive.Portal>
			<SelectPrimitive.Positioner
				alignItemWithTrigger={false}
				sideOffset={6}
				className="z-60"
			>
				<SelectPrimitive.Popup
					data-slot="select-content"
					className={cn(
						'max-h-72 min-w-64 overflow-hidden rounded-lg border bg-popover p-1 text-popover-foreground shadow-lg outline-none',
						className,
					)}
					{...props}
				>
					<SelectPrimitive.List className="max-h-64 overflow-y-auto">
						{children}
					</SelectPrimitive.List>
				</SelectPrimitive.Popup>
			</SelectPrimitive.Positioner>
		</SelectPrimitive.Portal>
	);
}

function SelectItem({
	className,
	children,
	...props
}: SelectPrimitive.Item.Props) {
	return (
		<SelectPrimitive.Item
			data-slot="select-item"
			className={cn(
				'relative flex cursor-default items-center rounded-md py-1.5 pr-2 pl-8 text-sm outline-none select-none data-disabled:pointer-events-none data-disabled:opacity-50 data-highlighted:bg-accent data-highlighted:text-accent-foreground',
				className,
			)}
			{...props}
		>
			<SelectPrimitive.ItemIndicator className="absolute left-2 flex size-4 items-center justify-center text-primary">
				<Check className="size-4" />
			</SelectPrimitive.ItemIndicator>
			<SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText>
		</SelectPrimitive.Item>
	);
}

export { Select, SelectContent, SelectItem, SelectTrigger, SelectValue };

// packages/ui-solid/base/select.tsx
import type { PolymorphicProps } from '@kobalte/core/polymorphic';
import * as SelectPrimitive from '@kobalte/core/select';
import { cn } from '@repo/shared/lib/utils';
import { cva } from 'class-variance-authority';
import type { JSX, ValidComponent } from 'solid-js';
import { splitProps } from 'solid-js';

export type SelectProps<T extends { value: string; label: string } | string> =
	SelectPrimitive.SelectRootProps<T>;
const Select = SelectPrimitive.Root;
const SelectValue = SelectPrimitive.Value;
const SelectHiddenSelect = SelectPrimitive.HiddenSelect;

type SelectTriggerProps<T extends ValidComponent = 'button'> =
	SelectPrimitive.SelectTriggerProps<T> & {
		class?: string | undefined;
		children?: JSX.Element;
	};

const SelectTrigger = <T extends ValidComponent = 'button'>(
	props: PolymorphicProps<T, SelectTriggerProps<T>>,
) => {
	const [local, others] = splitProps(props as SelectTriggerProps, [
		'class',
		'children',
	]);
	return (
		<SelectPrimitive.Trigger
			class={cn(
				'flex h-10 w-full items-center justify-between rounded-md border border-input bg-transparent px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
				local.class,
			)}
			{...others}
		>
			{local.children}
			<SelectPrimitive.Icon
				as="svg"
				xmlns="http://www.w3.org/2000/svg"
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="2"
				stroke-linecap="round"
				stroke-linejoin="round"
				class="size-4 opacity-50"
			>
				<path d="M8 9l4 -4l4 4" />
				<path d="M16 15l-4 4l-4 -4" />
			</SelectPrimitive.Icon>
		</SelectPrimitive.Trigger>
	);
};

type SelectContentProps<T extends ValidComponent = 'div'> =
	SelectPrimitive.SelectContentProps<T> & { class?: string | undefined };

const SelectContent = <T extends ValidComponent = 'div'>(
	props: PolymorphicProps<T, SelectContentProps<T>>,
) => {
	const [local, others] = splitProps(props as SelectContentProps, ['class']);
	return (
		<SelectPrimitive.Portal>
			<SelectPrimitive.Content
				class={cn(
					'relative z-50 min-w-32 overflow-hidden rounded-md border bg-popover text-popover-foreground shadow-md animate-in fade-in-80',
					local.class,
				)}
				{...others}
			>
				<SelectPrimitive.Listbox class="m-0 p-1" />
			</SelectPrimitive.Content>
		</SelectPrimitive.Portal>
	);
};

type SelectItemProps<T extends ValidComponent = 'li'> =
	SelectPrimitive.SelectItemProps<T> & {
		class?: string | undefined;
		children?: JSX.Element;
	};

const SelectItem = <T extends ValidComponent = 'li'>(
	props: PolymorphicProps<T, SelectItemProps<T>>,
) => {
	const [local, others] = splitProps(props as SelectItemProps, [
		'class',
		'children',
	]);
	return (
		<SelectPrimitive.Item
			class={cn(
				'relative mt-0 flex w-full cursor-default select-none items-center rounded-sm py-1.5 pl-2 pr-8 text-sm outline-none focus:bg-accent focus:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
				local.class,
			)}
			{...others}
		>
			<SelectPrimitive.ItemIndicator class="absolute right-2 flex size-3.5 items-center justify-center">
				<svg
					xmlns="http://www.w3.org/2000/svg"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
					stroke-linejoin="round"
					class="size-4"
				>
					<path stroke="none" d="M0 0h24v24H0z" fill="none" />
					<path d="M5 12l5 5l10 -10" />
				</svg>
			</SelectPrimitive.ItemIndicator>
			<SelectPrimitive.ItemLabel>{local.children}</SelectPrimitive.ItemLabel>
		</SelectPrimitive.Item>
	);
};

const labelVariants = cva(
	'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
	{
		variants: {
			variant: {
				label: 'data-[invalid]:text-destructive',
				description: 'font-normal text-muted-foreground',
				error: 'text-xs text-destructive',
			},
		},
		defaultVariants: {
			variant: 'label',
		},
	},
);

type SelectLabelProps<T extends ValidComponent = 'label'> =
	SelectPrimitive.SelectLabelProps<T> & {
		class?: string | undefined;
	};

const SelectLabel = <T extends ValidComponent = 'label'>(
	props: PolymorphicProps<T, SelectLabelProps<T>>,
) => {
	const [local, others] = splitProps(props as SelectLabelProps, ['class']);
	return (
		<SelectPrimitive.Label
			class={cn(labelVariants(), local.class)}
			{...others}
		/>
	);
};

type SelectDescriptionProps<T extends ValidComponent = 'div'> =
	SelectPrimitive.SelectDescriptionProps<T> & {
		class?: string | undefined;
	};

const SelectDescription = <T extends ValidComponent = 'div'>(
	props: PolymorphicProps<T, SelectDescriptionProps<T>>,
) => {
	const [local, others] = splitProps(props as SelectDescriptionProps, [
		'class',
	]);
	return (
		<SelectPrimitive.Description
			class={cn(labelVariants({ variant: 'description' }), local.class)}
			{...others}
		/>
	);
};

type SelectErrorMessageProps<T extends ValidComponent = 'div'> =
	SelectPrimitive.SelectErrorMessageProps<T> & {
		class?: string | undefined;
	};

const SelectErrorMessage = <T extends ValidComponent = 'div'>(
	props: PolymorphicProps<T, SelectErrorMessageProps<T>>,
) => {
	const [local, others] = splitProps(props as SelectErrorMessageProps, [
		'class',
	]);
	return (
		<SelectPrimitive.ErrorMessage
			class={cn(labelVariants({ variant: 'error' }), local.class)}
			{...others}
		/>
	);
};

export {
	Select,
	SelectContent,
	SelectDescription,
	SelectErrorMessage,
	SelectHiddenSelect,
	SelectItem,
	SelectLabel,
	SelectTrigger,
	SelectValue,
};
